### ISSUE TITLE
While adding styles for the text it won't applying. Rather than it's showing single character. 

### ISSUE THREAD

**Issue by vinay528** [doyeonOh/ngx-line-clamp#1]
Consider the below screenshot.
![image](https://user-images.githubusercontent.com/36846318/50895313-c606e280-142b-11e9-8c40-4bd3ce844a67.png)

**Comment by ryanOhh** [comment]
Could you explain it in more detail?

**Comment by eyalhakim** [comment]
@doyeonOh This happens to me as well on Edge.

**Comment by ryanOhh** [comment]
it was updated now.
