### ISSUE TITLE
Add output event if text was truncated

### ISSUE THREAD

**Issue by unlight** [doyeonOh/ngx-line-clamp#3]
Can we add output event if text was truncated?
I'm creating sort of expand component, I need to show/hide "show more" button if necessary.

**Comment by ryanOhh** [comment]
thanks for PR
I'll work on it this week.

**Comment by ryanOhh** [comment]
You can use textTruncated at ngx-line-clamp@1.3.0.


```html
<div ngx-line-clamp (textTruncated)="onTextTruncated($event)">
</div>
```
